### ISSUE TITLE
Seperate Tokio API in favour of adaptability.

### ISSUE THREAD

**Issue by ChillFish8** [awestlake87/pyo3-asyncio#2]
I think it would be a good idea to seperate the Tokio runtime and compents into a feature rather than a set - required item, some people may prefer to use smol due to it being a lighter runtime or async-std.

An idea solution would be to provide a runtime naive set of futures and tooling around it to allow this to be compatable with any rust runtime.

Another idea would probably also be to seperate the async rust runtime handling and python async handling as Python's async system is still perfectly interactable without async rust, giving a developer more feedom to choose how they want to design their system.

**Comment by awestlake87** [comment]
Yeah, correct me if I'm wrong, but I think the reason we talked about going with tokio was because we could control the initialization of the runtime to make it use the single-threaded scheduler.

I think my preference would be to remove the spawn and spawn_blocking functions from the public interface because they really don't really need to be there. But the main problem I see is selecting which spawn function to use internally with `into_coroutine`. This is hard to do with features since features are additive, not mutually exclusive.

Maybe what needs to happen is we extract the `into_coroutine`, and by association `run_until_complete`, functions into runtime-specific modules similar to what [async-tungstenite](https://github.com/sdroege/async-tungstenite) does. Each runtime-specific module would be enabled by an additive feature.

**Comment by awestlake87** [comment]
Let me know if you have any feedback on my changes in #3. I feature-gated tokio and added support for async-std. I haven't added any other runtimes yet, but these should act as a template for it.

**Comment by awestlake87** [comment]
Also, as an update, I generalized `into_coroutine`, `run_until_complete`, and `test_main` so that users can use generic runtimes with this library if pyo3-asyncio doesn't support them yet. Any runtime can be used provided the user implements the `JoinError` and `Runtime` traits for their executor.

I also changed `async-std` and `tokio` to use these more generic functions underneath to verify that they work properly and translate pretty well to other runtimes.

Tokio's runtime can also be customized now instead of locking it to the current-thread scheduler.

**Comment by ChillFish8** [comment]
Might be an idea todo something similar to how hyper.rs works with a generic executor.

**Comment by awestlake87** [comment]
Have you looked at the `Runtime` trait in [generic.rs](https://github.com/awestlake87/pyo3-asyncio/blob/other-runtimes/src/generic.rs)? I think it's similar to what hyper.rs does, except mine is a bit more complicated since I added join handles to catch panics.

**Comment by awestlake87** [comment]
@davidhewitt was looking to release `0.13.2` soon, so I was probably going to merge #3 today unless you had any extra feedback on it.

**Comment by ChillFish8** [comment]
Looks good, hopefully we'll get some more feedback aswell so we can see what works and what doesnt 👍

**Comment by awestlake87** [comment]
Awesome, I'll go ahead and merge it for now!
