### ISSUE TITLE
Document/Support !Send Futures

### ISSUE THREAD

**Issue by TkTech** [awestlake87/pyo3-asyncio#23]
Hello! I hope I'm not missing something obvious (new to Rust!), but it appears as if this can't be used with a `Future` that is `!Send`.

I'm wrapping some C code that is not thread-safe...

```rust
#[pyclass(unsendable)]
struct SomeClass {
   // Burried deep within this is a property that is !Send
   not_thread_safe: NotThreadSafe
}
...
#[pymethods]
impl SomeClass  {
    #[new]
    fn new() -> PyResult<Self> {
        ...
        // Calling this here since there's a process poll on the Python side.
        pyo3_asuncio::tokio::init_current_thread_once();
        ...
    }

    pub fn execute(&mut self) -> PyResult<PyObject> {
        pyo3_asyncio::tokio::into_coroutine(py, async move {
            // BOOM! "cannot be sent between threads safely", even though we're not moving anything between threads.
            self.not_thread_safe.execute().await;
            Python::with_gil(|py| Ok(py.None()))
        })
    }
}
```

`pyo3_asyncio` implements `tokio::init_current_thread_once()`, which should be perfect - it uses the current thread scheduler, which specifically allows `!Send` futures. On the python side, `asyncio` is single-threaded.

However, `into_coroutine` explicitly requires the `Send` trait, and so I'm in a bit of a pickle. I would expect this to just work.

Fantastic project by the way, drastically less boilerplate than doing this from C.

**Comment by awestlake87** [comment]
> pyo3_asyncio implements tokio::init_current_thread_once(), which should be perfect - it uses the current thread scheduler, which specifically allows !Send futures. On the python side, asyncio is single-threaded.
>
> However, into_coroutine explicitly requires the Send trait, and so I'm in a bit of a pickle. I would expect this to just work.

The reasoning behind this is a bit complicated. `pyo3-asyncio` doesn't unify the `asyncio` and `tokio` event loops, so while they can both be single threaded, they are not sharing the _same_ thread, hence the `Send` requirement. 

For example, if you were to call the `execute` function from within the `asyncio` event loop, then that future would have to be 'sent' to the `tokio` thread. There's not much you can do to get around that.

However, as long as `execute` is called within a `tokio::task::LocalSet`, the `asyncio.Task` that's returned by `into_coroutine` could be used by Python's event loop since `PyObject` implements `Send`. This is not possible through the current API, but I was able to add support for it to the [local-tasks](https://github.com/awestlake87/pyo3-asyncio/tree/local-tasks) branch if you want to check it out. Here's an example:

```rust
use std::{rc::Rc, time::Duration};

use pyo3::prelude::*;

/// Awaitable sleep function
#[pyfunction]
fn sleep_for(py: Python, secs: u64) -> PyResult<PyObject> {
    // Rc is non-send so it cannot be passed into pyo3_asyncio::tokio::into_coroutine
    let secs = Rc::new(secs);

    // into_coroutine will likely be changed to into_py_future in a future release, 
    // so the name here is based on the newer one.
    pyo3_asyncio::tokio::into_local_py_future(py, async move {
        tokio::time::sleep(Duration::from_secs(*secs)).await;
        Python::with_gil(|py| Ok(py.None()))
    })
}

#[pyo3_asyncio::tokio::main]
async fn main() -> PyResult<()> {
    // the main coroutine is running in a Send context, so we cannot use LocalSet here. Instead
    // we use spawn_blocking in order to use LocalSet::block_on
    tokio::task::spawn_blocking(|| {
        // LocalSet allows us to work with !Send futures within tokio. Without it, any calls to
        // pyo3_asyncio::tokio::into_local_py_future will panic.
        tokio::task::LocalSet::new().block_on(pyo3_asyncio::tokio::get_runtime(), async {
            Python::with_gil(|py| {
               let py_future = sleep_for(py, 1)?;
               pyo3_asyncio::into_future(py_future.as_ref(py))
            })?
            .await?;

            Ok(())
        })
    }).await.unwrap()
}
```

It's a bit restricting though, so I'm not sure if it'll meet your needs. If it doesn't then there might be some other options to work around the C bindings, but I'd probably need some more info to advise on that.

**Comment by TkTech** [comment]
This looks great!

> The reasoning behind this is a bit complicated. pyo3-asyncio doesn't unify the asyncio and tokio event loops, so while they can both be single threaded, they are not sharing the same thread, hence the Send requirement.

This is obvious in hindsight, but I initial misunderstood how this was working after reading "Why Two Event Loops". When reading that Python kept control of the main thread, I incorrectly assumed that pyo3-asyncio was maintaining two event loops, but ticking the `tokio` event loop from `asyncio`.

**Comment by awestlake87** [comment]
Awesome! If these changes solve your issue, I can add the missing impl for `async-std` and publish a patch release relatively quickly. Other users might benefit from these functions too.

**Comment by awestlake87** [comment]
Alright, I'm gearing up to release this as 0.13.4, but I had some last minute changes that I wanted to make:
- I renamed `into_local_py_future` to `local_future_into_py` since the new name for `into_coroutine` will most likely be `future_into_py`. I got them mixed up when I made these `spawn_local` changes.
- `local_future_into_py` now returns a `&PyAny` instead of `PyObject`.
