### ISSUE TITLE
Use Rust as python event loop?

### ISSUE THREAD

**Issue by LegNeato** [awestlake87/pyo3-asyncio#44]
This is more of a discussion, not a bug report. Please feel free to close.

The readme mentions just about every way to interact with python event loops, but one potential option missing is using tokio/async-std as the python event loop, similar to how uvloop can be used. That way all the rust code "just works" and you are running with rust in control of the main thread, runtime, and all futures.

Is this possible? If so what tradeoffs do you see?

**Comment by awestlake87** [comment]
Good question! This was an ongoing discussion since before this library was created. [This comment (especially the stuff under "Some Additional Thoughts")](https://github.com/awestlake87/pyo3-asyncio/issues/6#issuecomment-766793610) kinda sums up my thoughts on it at the time and provides some links to the discussions / projects related to this. The rest of the thread in #6 is relevant as well since it's proposing something similar: running Rust futures on Python's asyncio event loop instead. 

In short, there have been a few attempts in the past to unify the Python and Rust event loop, and while I do still think it's _possible_, it's definitely an undertaking. It's also not immediately clear whether this would have any significant performance wins over the current solution. It might seem like it should be more efficient intuitively, but the cost of the FFI boundary might dwarf the cost of the signaling we do between Rust and Python. It's also not something I'd be confident in undertaking by myself at the moment since I don't feel like I'm familiar enough with the intricacies of the Python event loop to do it correctly.

In my personal opinion, I think the best way to do it is to add a compatibility layer on top of an _existing_ rust runtime that allows it to be used in place of Python's event loop, and it sounds to me like you agree. Looks like this is what [PyO3 Tokio](https://github.com/PyO3/tokio) was meant to do, but for reasons I'm not aware of, the project was abandoned and archived a few years before this project was released. If you're interested in investigating this, that project is probably the best lead. I'd definitely be interested to see what you find!

### Potential Trade-Offs

Here are the trade-offs as I see them:

#### Replacing Python's Event Loop with Rust
- Applications only 
  - This project in its current state is probably better for writing native extensions for Python _because_ the Python and Rust event loops are separate. Python libraries should ideally work with any Python event loop, but this would force users to use our Rust event loop.
  > We would likely want to support the current conversions alongside this compatibility layer for users that write native extensions.
- Complexity 
  - This layer will be complex to write and costly to maintain.
- Uncertainty 
  - It's uncertain whether this will be efficient enough to outweigh the cost of developing and maintaining this layer.
  - I still don't know why PyO3 Tokio was abandoned. It's possible they had valid reasons to think that it shouldn't be done other than the ones I've mentioned here.

#### Replacing Rust's Event Loop with Python
- Performance 
  - This was never benchmarked in #6, but my suspicion is that the FFI cost for this approach would make it slower than the current approach
- Ecosystem 
  - Running Rust on Python event loop means that libraries written on top of `async-std` or `tokio` would probably not work out of the box. See [this comment](https://github.com/awestlake87/pyo3-asyncio/issues/6#issuecomment-769883555) for more details.
  > `async-std` has a compatibility layer for `tokio` that allows `tokio` futures to run on `async-std` instead. It's possible we could do this too.

**Comment by ShadowJonathan** [comment]
Reminder that the pyo3 tokio archived itself with [this cryptic issue](https://github.com/PyO3/tokio/issues/136)

**Comment by LegNeato** [comment]
Thank you for the response! Need to think about this some more and poke around.
