### ISSUE TITLE
How to preserve contextvars.Context?

### ISSUE THREAD

**Issue by gi0baro** [awestlake87/pyo3-asyncio#52]
Hi, I'm experimenting with `pyo3-asyncio` and it is not clear to me how to preserve [Context](https://docs.python.org/3/library/contextvars.html#contextvars.Context) – and, thus, use [ContextVar](https://docs.python.org/3/library/contextvars.html#contextvars.ContextVar)s – in Python<->Rust<->Python async calls.

Let say I write a super-simple cdylib: 

```rust
use pyo3::prelude::*;

#[pyfunction]
pub fn temp_ctx(callback: PyObject) -> PyResult<Py<PyAny>> {
    Python::with_gil(|py| {
        let v = callback.call1(py, ())?;
        Ok(v)
    })
}

#[pyfunction]
pub fn temp_ctx_async<'p>(py: Python<'p>, callback: PyObject) -> PyResult<&'p PyAny> {
    pyo3_asyncio::tokio::future_into_py(py, async move {
        Ok(Python::with_gil(|py| {
            let coro = callback.call1(py, ())?;
            pyo3_asyncio::tokio::into_future(coro.as_ref(py))
        })?.await?)
    })
}

#[pymodule]
fn temp(py: Python, module: &PyModule) -> PyResult<()> {
    module.add_function(wrap_pyfunction!(temp_ctx, module)?)?;
    module.add_function(wrap_pyfunction!(temp_ctx_async, module)?)?;

    pyo3::prepare_freethreaded_python();

    Ok(())
}
```

then the sync implementation preserves the context while the async one doesn't.

I tested the behaviour with this snippet:

```python
import asyncio
from contextvars import ContextVar, copy_context

cx = ContextVar("cx")

def cb():
    print("sync cb", list(copy_context().items()))
    return cx.get()

async def acb():
    await asyncio.sleep(0.1)
    print("async cb", list(copy_context().items()))
    return cx.get()

async def arunner():
    from temp import temp
    print("ctx async", list(copy_context().items()))
    await temp.temp_ctx_async(acb)

def run():
    from temp import temp
    print("ctx", list(copy_context().items()))
    v = temp.temp_ctx(cb)
    asyncio.run(arunner())

cx.set("foobar")
run()
```

which outputs:

```
ctx [(<ContextVar name='cx' at 0x105a8c810>, 'foobar')]
sync cb [(<ContextVar name='cx' at 0x105a8c810>, 'foobar')]
ctx async [(<ContextVar name='cx' at 0x105a8c810>, 'foobar')]
async cb []
```

and then raises `LookupException` for the `cx` var.

**Comment by awestlake87** [comment]
Looks like this is an oversight on my part (sorry!).

It's likely that the Rust future is not aware of the Python context since it is spawned on a Rust thread. Ideally this should be handled transparently in the conversions similar to how we manage event loop references. I'll try to get this fixed and tested ASAP. 

I'm pretty sure I know where things are going wrong, so hopefully I'll have this working by tomorrow!

**Comment by awestlake87** [comment]
This should be fixed on the `contextvars` branch now. Unfortunately it involves some modifications to the public API, but you probably won't have to worry about those changes unless you're doing something a bit odd. 

Because of the API changes, it might not be released for a little while (seems like pyo3 is ramping up for a 0.15 release soon, but usually it takes a little while to finalize things).

Let me know if those changes work for you!

**Comment by awestlake87** [comment]
Also, I guess I should mention that I haven't touched up the docs yet so there may be some missing / wrong info in there. I'm planning on doing a more in-depth review when I've got all the 0.15 changes together.

**Comment by gi0baro** [comment]
@awestlake87 I confirm `contextvars` branch works correctly. Thank you!

**Comment by awestlake87** [comment]
0.15.0 is live with these changes now! There might be a few minor differences between the version you're using and the one that was released, so let me know if you run into any problems.

**Comment by gi0baro** [comment]
LGTM. Thanks!
