### ISSUE TITLE
Using pyo3-asyncio with webservice (actix-web / axum)

### ISSUE THREAD

**Issue by philschmid** [awestlake87/pyo3-asyncio#60]
I am currently trying to use `pyo3-asyncio` & `pyo3` together with a web service (axum). My goal is to execute python code in my route handler using `Python::with_gil` and `pyo3_asyncio::tokio::into_future`, but with this i ran into 
```Bash
sys:1: RuntimeWarning: coroutine 'handle' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: PyErr { type: <class 'RuntimeError'>, value: RuntimeError('no running event loop'), traceback: None }', src/main.rs:37:6
```

Example on how to reproduce: 

```rust

async fn test_route() -> &'static str {
    let fut = Python::with_gil(|py| {
        let asyncio = py.import("asyncio")?;

        // convert asyncio.sleep into a Rust Future
        pyo3_asyncio::tokio::into_future(asyncio.call_method1("sleep", (1.into_py(py),))?)
    })
    .unwrap();

    println!("sleeping for 1s");
    fut.await.unwrap();
    println!("done");
    "Response"
}

#[pyo3_asyncio::tokio::main]
async fn main() -> PyResult<()> {
    let app = Router::new().route("/test", post(test_route));
    
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
    Ok(())
}
```
Has anyone an idea on how to get this to work?

**Comment by awestlake87** [comment]
I believe the problem here is that internally, either actix-web or axum is spawning your `test_route` coroutine on the tokio runtime without making it aware of the python event loop (if you want to know why this is necessary, check out [this section](https://awestlake87.github.io/pyo3-asyncio/master/doc/pyo3_asyncio/#event-loop-references-and-contextvars) of the docs).

Essentially, what you need to do is ensure that every handler is aware of the python event loop. You can do this by taking the current pyo3_asyncio context in main, and scoping your handler with it:

```rust
use axum::{routing::post, Router};
use pyo3::prelude::*;
use std::net::SocketAddr;

async fn test_route() -> &'static str {
    let fut = Python::with_gil(|py| {
        let asyncio = py.import("asyncio")?;

        // convert asyncio.sleep into a Rust Future
        pyo3_asyncio::tokio::into_future(asyncio.call_method1("sleep", (1.into_py(py),))?)
    })
    .unwrap();

    println!("sleeping for 1s");
    fut.await.unwrap();
    println!("done");
    "Response"
}

#[pyo3_asyncio::tokio::main]
async fn main() -> PyResult<()> {
    let locals = Python::with_gil(|py| pyo3_asyncio::tokio::get_current_locals(py))?;

    let app = Router::new().route(
        "/test",
        post(move || pyo3_asyncio::tokio::scope(locals.clone(), test_route())),
    );
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
    Ok(())
}
```

This might get a little awkward as your router gets bigger, but I imagine you should be able to make some convenience helpers for the `axum::handler::Handler` trait that would clean that up if needed.

**Comment by philschmid** [comment]
@awestlake87 sorry it took some time to get back to your response. I can confirm your snippet works! 
Thank you!
